### ISSUE TITLE
July PR Challenge

### ISSUE THREAD

**Issue by lejeunerenard** [EntropyOrg/p5-Data-Frame#20]
I've been assigned this module as part of the [PR Challenge](http://cpan-prc.org/) and just wanted to check in to see if there was anything particular you would like done.

I see there are plenty of issues for future features, so if I don't hear from you soon, I'll do my best to tackle one of those features. :)

**Comment by zmughal** [comment]
Oh wow, what a coincidence! I just popped in here to look at the issues and you *just now* posted here! I've been busy lately and you came at just the right time. ;-)

Well, one thing that might be easy to start off with is this issue: <https://github.com/EntropyOrg/p5-Data-Frame/issues/15>. I currently use Tie::IxHash in the Data::Frame module in order to keep a hash table of all the columns, but Hash::Ordered seems faster and has a cleaner interface. That might be a slightly involved refactoring, but not too bad, I think.

Even easier than that might be to replace the error messages such as `ERROR_KEY_LENGTH_MISMATCH` and `"incorrect number of levels"` with exception classes made through <https://metacpan.org/release/failures>. That way they don't depend on the contents of the strings.

Let me know if you have any questions!

**Comment by lejeunerenard** [comment]
Awesome! Glad I caught you. Those both sound like great projects. I've learned a bit about `Hash::Ordered` and it sounds really awesome so I'll probably try that refactoring first. But who knows, maybe I'll do both. :)

I'll report back if I have any questions or when I've completed my PR to close this issue.

**Comment by omega** [comment]
Hey, I've been assigned this dist for the 2016 january pull request challenge, and since I see a pull request for the Hash::Ordered stuff, I'll try to tackle exception objects using `failures`
